## 8 Queens Problem - Solving Using the Genetic Algorithm
   ### The steps followed are listed below
      1. Create a Population for eg n= 100 . This will serve as the Initial Population. For the population, a new offspring population has to be computed using crossover.
      2. Randomly choose two parents to generate an Offspring. This Process is called Crossover.
      3. Perform Mutation

In [1]:
import numpy as np
import sys

In [2]:
nQueens = 8
STOP_CTR = 28
MUTATE_RATE = 0.00005
MUTATE_FLAG = True
MAX_ITER = 100000
POPULATION = None

In [3]:
class Setup:
	def __init__(self):
		self.seq = None
		self.fit = None
		self.surv = None
	def setSeq(self, val):
		self.seq = val
	def setFit(self, fitness):
		self.fit = fitness
	def setSurv(self, val):
		self.surv = val
	def getAttr(self):
		return {'sequence':seq, 'fitness':fit, 'survival':surv}

In [4]:
def fitness_fn(chromosome = None):
	clashes = 0;
	row_col_clashes = abs(len(chromosome) - len(np.unique(chromosome)))
	clashes += row_col_clashes

	# calculate diagonal clashes
	for i in range(len(chromosome)):
		for j in range(len(chromosome)):
			if ( i != j):
				dx = abs(i-j)
				dy = abs(chromosome[i] - chromosome[j])
				if(dx == dy):
					clashes += 1


	return 28 - clashes	

In [5]:
def generateSequence():
	# randomly generates a sequence of board states.
	global nQueens
	init_distribution = np.arange(nQueens)
	np.random.shuffle(init_distribution)
	return init_distribution

In [6]:
def generatePopulation(population_size = 100):
	global POPULATION

	POPULATION = population_size

	population = [Setup() for i in range(population_size)]
	for i in range(population_size):
		population[i].setSeq(generateSequence())
		population[i].setFit(fitness_fn(population[i].seq))

	return population

In [7]:
def getParent():
	globals()	
	parent1, parent2 = None, None
	
	summation_fitness = np.sum([x.fit for x in population])
	for each in population:
		each.surv = each.fit/(summation_fitness*1.0)

	while True:
		parent1_random = np.random.rand()
		parent1_rn = [x for x in population if x.surv <= parent1_random]
		try:
			parent1 = parent1_rn[0]
			break
		except:
			pass

	while True:
		parent2_random = np.random.rand()
		parent2_rn = [x for x in population if x.surv <= parent2_random]
		try:
			t = np.random.randint(len(parent2_rn))
			parent2 = parent2_rn[t]
			if parent2 != parent1:
				break
			else:
				print("Same parents")
				continue
		except:
			print("exception")
			continue

	if parent1 is not None and parent2 is not None:
		return parent1, parent2
	else:
		sys.exit(-1)

In [8]:
def crossover(parent1, parent2):
	globals()
	n = len(parent1.sequence)
	c = np.random.randint(n, size=1)
	child = Setup()
	child.seq = []
	child.seq.extend(parent1.seq[0:c])
	child.seq.extend(parent2.seq[c:])
	child.setFit(fitness(child.seq))
	return child

In [9]:
def mutatation(child):
  globals()
  if child.surv < MUTATE_RATE:
    c = np.random.randint(nQueens)
    child.seq[c] = np.random.randint(nQueens)
    return child

In [10]:
def GeneticAlgorithm(iteration):
	print (" $"*10 ,"Genetic Evolution : ", iteration , " $"*10)
	globals()
	newpopulation = []
	for i in range(len(population)):
		parent1, parent2 = getParent()
		# print "Parents generated : ", parent1, parent2

		child = crossover(parent1, parent2)

		if(MUTATE_FLAG):
			child = mutatation(child)

		newpopulation.append(child)
	return newpopulation

In [11]:
def stop():
	globals()
	fitnessvals = [pos.fit for pos in population]
	if STOP_CTR in fitnessvals:
		return True
	if MAX_ITER == iteration:
		return True
	return False

In [12]:
population = generatePopulation(1000)

#print ("POPULATION size : ", population)

iteration = 0;
while not stop():
	# keep iteratin till  you find the best position
	population = GeneticAlgorithm(iteration)
	iteration +=1 

print ("Iteration number : ", iteration)
for each in population:
	if each.fit == 28:
		print (each.seq)

Iteration number :  0
[5 7 1 3 0 6 4 2]
[2 5 7 0 4 6 1 3]
[0 5 7 2 6 3 1 4]
[3 6 0 7 4 1 5 2]
